name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests (all)
        run: npx cypress run
        env:
          CYPRESS_CI: true
      - name: Run Cypress tests with tag (cenariosPositivos)
        run: npx cypress run --env grep=cenariosPositivos
        env:
          CYPRESS_CI: true
      - name: Run Cypress tests with tag (regressivo)
        run: npx cypress run --env grep=regressivo
        env:
          CYPRESS_CI: true
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos